Master task1
nnagornyy/html_sedona pull request #2
Opened 2019-11-18 00:09 UTC by Olesya1311

проверить разметку

2019-11-20 10:29 UTC, nnagornyy requested changes
В целом все хорошо, страницы с формой и галереи без принтезий

2019-11-20 10:29 UTC, nnagornyy commented on index.html
> +                <img class="page-header__logo-img page-header__logo-img--mobile" src="img/logotype-mobile.svg" width="102" height="83" alt="Sedona">
Почитай вот про это: 
https://developer.mozilla.org/ru/docs/Web/HTML/Element/picture
Я думаю это использовать такой подход в данном случае будет лучше

2019-11-20 10:29 UTC, nnagornyy commented on index.html
> +            <section class="main-photo">
Данный блок универсальный для каждой страницы, стоит сделать это универсальнее: его вид зависит только от высоты контента внутри него

2019-11-20 10:29 UTC, nnagornyy commented on index.html
> +                <div class="main-photo__mask"></div>
Маска это псеводоэлемент  after

2019-11-20 10:29 UTC, nnagornyy commented on index.html
> +                <ul class="advantage-list">
Стоит подумать о рефакторинге данного блока, мы с тобой обсуждали 
1. Нету лаканичностии
2. Сложно будет вынести 1 секцию на другую страницу (нет модульности)

2019-11-20 10:29 UTC, nnagornyy commented on form.html
> +            <section class="inner-photo">
Универсальный блок для всех страниц где есть фото вверху

2019-11-23 17:37 UTC, Olesya1311 commented on index.html
> +            <section class="main-photo">
ок

2019-11-23 17:37 UTC, Olesya1311 commented on index.html
> +                <img class="page-header__logo-img page-header__logo-img--mobile" src="img/logotype-mobile.svg" width="102" height="83" alt="Sedona">
исправила, более подробно в следующем запросе

2019-11-23 17:37 UTC, Olesya1311 commented on index.html
> +                <div class="main-photo__mask"></div>
ок

2019-11-23 17:37 UTC, Olesya1311 commented on form.html
> +            <section class="inner-photo">
ок

2019-11-23 17:55 UTC, Olesya1311 commented on index.html
> +                <ul class="advantage-list">
готово

2019-11-23 17:59 UTC, merged